import yagmail
import pandas as pd
import numpy as np

class email_sender:
    def __init__(self,to,body,attach,sub):
        self.to = to
        self.body = body
        self.attach = attach
        self.sub = sub
        self.processing()

    def processing(self):
        self.register()
        self.send()


    def register(self):
        yagmail.register("architecttbdprojects@gmail.com","Karthick@2506")

    def send(self):
        self.yag = yagmail.SMTP("architecttbdprojects@gmail.com")
        self.yag.send(to=self.to,subject=self.sub, contents=self.body,attachments=self.attach)
        #self.yag.send(to=self.to, subject=self.sub, contents=self.body)


class email_generator:
    def __init__(self,data,email_mapping):
        self.data = pd.read_excel(data)
        self.email_mapping = pd.read_excel(email_mapping)
        self.body = """Hi ?????,

                               This is to notify that following project's ranking in ARchitect appear as 'Other/TBD':

                               !!!!

                               Please update the ranking with latest values.

                               This is an autogenerated email, please do not reply.

                               Thanks,
                               KARthick K"""
        self.subject = "Updating Project Ranking in ARchitect"
        self.default_projects = {}
        self.processing()

    def processing(self):
        self.identify_defaultors()
        self.create_files()


    def identify_defaultors(self):
        self.data = self.data[self.data['Ranking']=='Other / TBD']
        self.data['Project_Title'] = self.data['Project Id'].astype("str") + ":" + self.data['Title']
        self.defaultors = self.data['Created By'].unique()


    def create_files(self):
        for i in self.defaultors:
            self.data[self.data['Created By'] == i].to_html("C:\\AR\\email project\\" + i + ".html")
            self.default_projects[i] = list(self.data['Project_Title'].unique())
            email_sender([self.email_mapping[self.email_mapping['Name']==i]['email'][0],"karthico@in.ibm.com","kk_mechcrick@yahoo.co.in"],self.body.replace("?????",i).replace("!!!!",str(self.default_projects[i])),"C:\\AR\\email project\\" + i + ".html",self.subject)








if __name__ == "__main__":
    # users = ['architecttbdprojects@gmail.com','tarunhariharan60@gmail.com','kk.or.karthick@gmail.com',"kk_mechcrick@yahoo.co.in","karthico@in.ibm.com"]
    # body = """Hi ????,
    #           This is to notify that following projects have ranking as "Other/TBD" in ARchitect.
    #           Please update them to show up in latest MQ change reports
    #           This is System generated message, please do not reply.
    #           Thanks,
    #           ARvind"""
    # subject = "Project Status Update Notification"
    # attachment = "C:\\Users\\KarthickK\\Downloads\\brochure.pdf"
    # for i in users:
    #     email_sender(i,body.replace("????",i.replace("@gmail.com","")),attachment,subject)
    email_generator("C:\\AR\\email project\\Projects_test.xlsx","C:\\AR\\email project\\email_mapping.xlsx")